<a href="https://colab.research.google.com/github/2303A51042/23CSBTB29/blob/main/LAB1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr =np.array([1,9,5,8])
print(np.sort(arr))

[1 5 8 9]


In [5]:
import numpy as np
a = np.array([1,2,3])
b = np.array([5,6,7])
c = (a+b)
print(c)

[ 6  8 10]


In [6]:
import numpy as np
arr = np.array([1,2,5,7])
sumofarr = np.sum(arr)
print(f"sum is: {sumofarr}")

sum is: 15


In [3]:
import numpy as np
a = np.array([1,2,3])
b = np.array([5,6,7])
c = (a-b)
print(c)

[-4 -4 -4]


In [2]:
import numpy as np
a = np.array([1,2,3])
b = np.array([5,6,7])
c = (a*b)
print(c)

[ 5 12 21]
